"use client";

import { useState } from "react";
import { CheckCircle2, Cloud, Download, RefreshCw, ShieldCheck } from "lucide-react";
import { buildSyncBatch, downloadSnapshot, syncToApi, type SnapshotMode } from "@/lib/api-client";
import { useApiStore } from "@/store/use-api-store";

export function ApiSettings({ onToast }: { onToast: (message: string) => void }) {
  const state = useApiStore(); const [draft, setDraft] = useState({ baseUrl: state.baseUrl, accessToken: state.accessToken, snapshotToken: state.snapshotToken, enabled: state.enabled, mode: state.mode, from: state.from, to: state.to }); const [busy, setBusy] = useState(false);
  const save = () => { state.setSettings(draft); onToast("Настройки API сохранены"); };
  const sync = async () => { save(); const pendingCount = Object.values(buildSyncBatch()).reduce((sum, rows) => sum + rows.length, 0); if (!draft.enabled || !draft.baseUrl || !draft.accessToken) { state.setStatus({ status: "offline", lastError: "Укажи API URL, включи синхронизацию и добавь access token.", pendingCount }); return; } setBusy(true); state.setStatus({ status: "checking", lastError: "", pendingCount }); try { const result = await syncToApi(draft); state.setStatus({ status: "online", lastError: "", lastSyncAt: result.syncedAt, pendingCount: 0 }); onToast(`Синхронизировано записей: ${result.accepted}`); } catch { state.setStatus({ status: "error", lastError: "API недоступен. Локальные данные сохранены; повтори позже.", pendingCount }); onToast("Синхронизация не удалась, данные остались локально"); } finally { setBusy(false); } };
  const snapshot = async () => { save(); setBusy(true); try { const payload = await downloadSnapshot(draft, draft.mode); const count = ["transactions", "calls", "leads", "offers", "followUps"].reduce((sum, key) => sum + (Array.isArray(payload[key]) ? payload[key].length : 0), 0); const period = `${draft.from || "начало"} — ${draft.to || "сегодня"}`; state.setStatus({ lastSnapshotAt: new Date().toISOString(), lastSnapshotInfo: `версия ${String(payload.version ?? "v1")} · период ${period} · записей ${count}` }); onToast("Snapshot скачан для ручной передачи в ChatGPT"); } catch { onToast("Snapshot не удалось скачать"); } finally { setBusy(false); } };
  return <section className="api-settings-card"><div className="api-settings-heading"><div><p className="eyebrow">OPTIONAL API · LOCAL-FIRST</p><h2>Railway API и snapshot</h2><p className="muted">API необязателен: без него приложение продолжает работать локально.</p></div><ShieldCheck size={24} /></div><div className="api-settings-grid"><label><span>API URL</span><input value={draft.baseUrl} onChange={(event) => setDraft({ ...draft, baseUrl: event.target.value })} placeholder="https://personal-tracker-api.up.railway.app" /></label><label><span>JWT access token</span><input type="password" value={draft.accessToken} onChange={(event) => setDraft({ ...draft, accessToken: event.target.value })} placeholder="Вставь токен после login" /></label><label><span>Read-only snapshot token</span><input type="password" value={draft.snapshotToken} onChange={(event) => setDraft({ ...draft, snapshotToken: event.target.value })} placeholder="Не обязателен для локального режима" /></label><label><span>Режим snapshot</span><select value={draft.mode} onChange={(event) => setDraft({ ...draft, mode: event.target.value as SnapshotMode })}><option value="summary">summary · безопасные агрегаты</option><option value="full">full · личный полный экспорт</option></select></label><label><span>Период от</span><input type="date" value={draft.from} onChange={(event) => setDraft({ ...draft, from: event.target.value })} /></label><label><span>Период до</span><input type="date" value={draft.to} onChange={(event) => setDraft({ ...draft, to: event.target.value })} /></label></div><label className="api-toggle"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} /> Включить синхронизацию с API</label><div className="api-status-row"><span><Cloud size={15} /> {state.status === "online" ? "API доступен" : state.status === "checking" ? "Проверяю API…" : state.status === "error" ? "Ошибка API" : "API не подключён"}</span><small>Последняя синхронизация: {state.lastSyncAt ? new Date(state.lastSyncAt).toLocaleString("ru-RU") : "нет"} · ожидает: {state.pendingCount}</small></div>{state.lastError && <p className="api-error">{state.lastError}</p>}<div className="settings-actions"><button className="button-primary" onClick={save}><CheckCircle2 size={16} /> Сохранить</button><button className="button-secondary" onClick={sync} disabled={busy}><RefreshCw size={16} /> Синхронизировать сейчас</button><button className="button-secondary" onClick={snapshot} disabled={busy}><Download size={16} /> Скачать snapshot для анализа</button></div>{state.lastSnapshotAt && <small className="muted">Snapshot сформирован: {new Date(state.lastSnapshotAt).toLocaleString("ru-RU")}. {state.lastSnapshotInfo}. ChatGPT автоматически к API не подключён — файл передаётся вручную.</small>}</section>;
}
