/// Human-labelled acceptance corpus. The labels, rather than parser output,
/// define what this shadow experiment is allowed to call understood.
class SemanticFixture {
  const SemanticFixture(
      {required this.id,
      required this.language,
      required this.input,
      required this.intent,
      required this.projection,
      required this.supported,
      required this.unresolved,
      required this.extracted,
      required this.mustNotInfer,
      required this.ambiguity,
      required this.multiEvent,
      required this.risk});
  final String id, language, input, intent, projection, ambiguity, risk;
  final bool supported, multiEvent;
  final Set<String> unresolved, mustNotInfer;
  final Map<String, String> extracted;
}

SemanticFixture _m(String l, int n, String input, String direction,
        String amount, String currency,
        {bool supported = true,
        bool multi = false,
        String ambiguity = 'none'}) =>
    SemanticFixture(
        id: '$l-money-${n.toString().padLeft(2, '0')}',
        language: l,
        input: input,
        intent: 'money.$direction',
        projection: 'moneyTransaction',
        supported: supported,
        unresolved: supported ? {'account', 'category'} : {'intent'},
        extracted:
            supported ? {'minorUnits': amount, 'currency': currency} : const {},
        mustNotInfer: {'accountId'},
        ambiguity: ambiguity,
        multiEvent: multi,
        risk: 'financial');
SemanticFixture _d(String l, int n, String input, String intent,
        {bool supported = true,
        String projection = 'sportSetCandidate',
        Set<String> unresolved = const {}}) =>
    SemanticFixture(
        id: '$l-${intent.split('.').first}-${n.toString().padLeft(2, '0')}',
        language: l,
        input: input,
        intent: intent,
        projection: projection,
        supported: supported,
        unresolved: unresolved,
        extracted: const {},
        mustNotInfer: const {'canonicalId'},
        ambiguity: unresolved.isEmpty ? 'none' : 'known_unresolved',
        multiEvent: false,
        risk: 'non_financial');
SemanticFixture _x(String l, int n, String input, {bool multi = false}) =>
    SemanticFixture(
        id: '$l-adversarial-${n.toString().padLeft(2, '0')}',
        language: l,
        input: input,
        intent: 'generic.unsupported',
        projection: 'unsupported',
        supported: false,
        unresolved: const {'intent'},
        extracted: const {},
        mustNotInfer: const {'amount', 'accountId'},
        ambiguity: multi ? 'multi_event' : 'unknown_or_malformed',
        multiEvent: multi,
        risk: 'high');

final semanticCorpus = <SemanticFixture>[
  // 40 Russian: 15 money, 7 sport, 7 work, 5 English, 6 adversarial.
  _m('ru', 1, 'потратил 20 тысяч на колу', 'expense', '20000', 'UZS'),
  _m('ru', 2, 'купил кофе за 20к', 'expense', '20000', 'UZS'),
  _m('ru', 3, 'заплатил 150 тысяч наличными', 'expense', '150000', 'UZS'),
  _m('ru', 4, 'оплатил 1.5 млн сум за ремонт', 'expense', '1500000', 'UZS'),
  _m('ru', 5, 'отдал 5 лямов за машину', 'expense', '5000000', 'UZS'),
  _m('ru', 6, 'получил зарплату 5 млн', 'income', '5000000', 'UZS'),
  _m('ru', 7, 'пришло 300 тысяч', 'income', '300000', 'UZS'),
  _m('ru', 8, 'мне перевели 20 баксов', 'income', '2000', 'USD'),
  _m('ru', 9, 'потратил 50 долларов на обед', 'expense', '5000', 'USD'),
  _m('ru', 10, r'купил билет $10.99', 'expense', '1099', 'USD'),
  _m('ru', 11, 'заработал 0.01 USD', 'income', '1', 'USD'),
  _m('ru', 12, 'оплатил 999999999999 сум', 'expense', '999999999999', 'UZS'),
  _m('ru', 13, 'потратил 1,5 млн сум', 'expense', '1500000', 'UZS'),
  _m('ru', 14, 'получил 20к', 'income', '20000', 'UZS'),
  _m('ru', 15, 'купил еду за 120000 картой', 'expense', '120000', 'UZS'),
  _d('ru', 1, 'жим 80 на 8', 'sport.detailed_set', unresolved: {'exerciseId'}),
  _d('ru', 2, 'присед 100 кг 6 раз', 'sport.detailed_set',
      unresolved: {'exerciseId'}),
  _d('ru', 3, 'пробежал 5 км', 'sport.activity'),
  _d('ru', 4, 'баскетбол 90 минут', 'sport.activity'),
  _d('ru', 5, 'играл в теннис 40 минут', 'sport.activity'),
  _d('ru', 6, 'жим 60x10', 'sport.detailed_set', unresolved: {'exerciseId'}),
  _d('ru', 7, 'присед 70 на 12', 'sport.detailed_set',
      unresolved: {'exerciseId'}),
  _d('ru', 1, 'позвонил клиенту', 'work.interaction',
      projection: 'workInteraction'),
  _d('ru', 2, 'завтра написать директору', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('ru', 3, 'созвон с клиентом', 'work.interaction',
      projection: 'workInteraction'),
  _d('ru', 4, 'перезвонить клиенту завтра', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('ru', 5, 'позвонил директору', 'work.interaction',
      projection: 'workInteraction'),
  _d('ru', 6, 'завтра позвонить клиенту', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('ru', 7, 'созвон завтра в 15:00', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('ru', 1, 'занимался английским 40 минут', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('ru', 2, 'выучил 20 английских слов', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('ru', 3, 'английский 30 минут', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('ru', 4, 'словарь English 15 минут', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('ru', 5, 'учил английский', 'english.learning_activity',
      projection: 'englishActivity'),
  _x('ru', 1, ''),
  _x('ru', 2, 'только 20'),
  _x('ru', 3, 'купил кофе 20к и такси 30к', multi: true),
  _x('ru', 4, 'потратил 1..5 сум'),
  _x('ru', 5, 'получил -20 долларов'),
  _x('ru', 6, 'какая-то хрень'),
  // 40 Uzbek: 15 money, 6 sport, 7 work, 5 English, 7 adversarial.
  _m('uz', 1, "20 ming so'm kola uchun sarfladim", 'expense', '20000', 'UZS'),
  _m('uz', 2, "150 ming karta orqali toladim", 'expense', '150000', 'UZS'),
  _m('uz', 3, 'naqd 30 ming tushlikka sarfladim', 'expense', '30000', 'UZS'),
  _m('uz', 4, 'maosh oldim 5 mln', 'income', '5000000', 'UZS'),
  _m('uz', 5, '50 dollar toladim', 'expense', '5000', 'USD'),
  _m('uz', 6, '1,5 mln som sarfladim', 'expense', '1500000', 'UZS'),
  _m('uz', 7, '20k kofega sarfladim', 'expense', '20000', 'UZS'),
  _m('uz', 8, 'kelib tushdi 300 ming', 'income', '300000', 'UZS'),
  _m('uz', 9, r'oldim $500', 'income', '50000', 'USD'),
  _m('uz', 10, 'sotib oldim 120000 somga', 'expense', '120000', 'UZS'),
  _m('uz', 11, 'berdim 5 million', 'expense', '5000000', 'UZS'),
  _m('uz', 12, 'maosh 999999999999 som tushdi', 'income', '999999999999',
      'UZS'),
  _m('uz', 13, 'sarfladim 0.01 USD', 'expense', '1', 'USD'),
  _m('uz', 14, 'tushdi 20 ming', 'income', '20000', 'UZS'),
  _m('uz', 15, 'toladim 10.99 dollar', 'expense', '1099', 'USD'),
  _d('uz', 1, 'bench 80x8', 'sport.detailed_set', unresolved: {'exerciseId'}),
  _d('uz', 2, '100 kg 6 marta squat', 'sport.detailed_set',
      unresolved: {'exerciseId'}),
  _d('uz', 3, '5 km yugurdim', 'sport.activity'),
  _d('uz', 4, '90 daqiqa basketbol', 'sport.activity'),
  _d('uz', 5, 'bosdim 60 ga 10', 'sport.detailed_set',
      unresolved: {'exerciseId'}),
  _d('uz', 6, 'tennis 40 daqiqa', 'sport.activity'),
  _d('uz', 1, "mijozga ertaga qo'ng'iroq qilish", 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('uz', 2, 'direktorga yozish kerak', 'work.follow_up',
      projection: 'workInteraction'),
  _d('uz', 3, "mijozga qo'ng'iroq qildim", 'work.interaction',
      projection: 'workInteraction'),
  _d('uz', 4, 'ertaga call Hasan', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('uz', 5, 'mijoz bilan call', 'work.interaction',
      projection: 'workInteraction'),
  _d('uz', 6, 'ertaga direktorga yozish', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('uz', 7, "qo'ng'iroq mijozga", 'work.interaction',
      projection: 'workInteraction'),
  _d('uz', 1, 'ingliz tili 30 daqiqa', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('uz', 2, "20 ta ingliz soz yodladim", 'english.learning_activity',
      projection: 'englishActivity'),
  _d('uz', 3, 'English 40 daqiqa', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('uz', 4, 'ingliz words oqidim', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('uz', 5, 'ingliz tili', 'english.learning_activity',
      projection: 'englishActivity'),
  _x('uz', 1, '???'),
  _x('uz', 2, '20 ming 30 ming'),
  _x('uz', 3, 'sarfladim 1..5 som'),
  _x('uz', 4, 'maosh -5 mln'),
  _x('uz', 5, 'kola 20 ming va taksi 30 ming sarfladim', multi: true),
  _x('uz', 6, 'nima gap'),
  _x('uz', 7, '0 som toladim'),
  // 40 English: 15 money, 7 sport, 6 work, 5 English, 7 adversarial.
  _m('en', 1, 'spent 20k on coffee', 'expense', '20000', 'UZS'),
  _m('en', 2, 'paid 15 dollars for lunch', 'expense', '1500', 'USD'),
  _m('en', 3, 'got paid 500 dollars', 'income', '50000', 'USD'),
  _m('en', 4, 'received salary 2k', 'income', '2000', 'UZS'),
  _m('en', 5, r'bought coffee for $10.99', 'expense', '1099', 'USD'),
  _m('en', 6, 'spent 1.5 million UZS', 'expense', '1500000', 'UZS'),
  _m('en', 7, 'paid 20 USD cash', 'expense', '2000', 'USD'),
  _m('en', 8, 'earned 0.01 USD', 'income', '1', 'USD'),
  _m('en', 9, 'received 999999999999 UZS', 'income', '999999999999', 'UZS'),
  _m('en', 10, 'spent 20k by card', 'expense', '20000', 'UZS'),
  _m('en', 11, 'paid 1,5 mln UZS', 'expense', '1500000', 'UZS'),
  _m('en', 12, r'received $20', 'income', '2000', 'USD'),
  _m('en', 13, 'spent 120000 on taxi', 'expense', '120000', 'UZS'),
  _m('en', 14, 'got paid 10.99 dollars', 'income', '1099', 'USD'),
  _m('en', 15, 'bought lunch for 150 ming', 'expense', '150000', 'UZS'),
  _d('en', 1, 'bench 80x8', 'sport.detailed_set', unresolved: {'exerciseId'}),
  _d('en', 2, 'squat 100 kg 6', 'sport.detailed_set',
      unresolved: {'exerciseId'}),
  _d('en', 3, 'ran 5 km', 'sport.activity'),
  _d('en', 4, 'basketball 90 minutes', 'sport.activity'),
  _d('en', 5, 'tennis 40 minutes', 'sport.activity'),
  _d('en', 6, 'bench 60x10', 'sport.detailed_set', unresolved: {'exerciseId'}),
  _d('en', 7, 'ran 10 km', 'sport.activity'),
  _d('en', 1, 'called John', 'work.interaction', projection: 'workInteraction'),
  _d('en', 2, 'call John tomorrow', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('en', 3, 'client asked to call tomorrow', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('en', 4, 'called client', 'work.interaction',
      projection: 'workInteraction'),
  _d('en', 5, 'call Hasan at 3 pm', 'work.interaction',
      projection: 'workInteraction'),
  _d('en', 6, 'tomorrow call director', 'work.follow_up',
      projection: 'workInteraction', unresolved: {'dueDate'}),
  _d('en', 1, 'practiced English for 40 minutes', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('en', 2, 'learned 20 English words', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('en', 3, 'English 30 minutes', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('en', 4, 'studied English', 'english.learning_activity',
      projection: 'englishActivity'),
  _d('en', 5, 'English words', 'english.learning_activity',
      projection: 'englishActivity'),
  _x('en', 1, 'just a number'),
  _x('en', 2, 'emoji 🤤'),
  _x('en', 3, 'spent 1..5 USD'),
  _x('en', 4, 'received -20 dollars'),
  _x('en', 5, r'spent $10 lunch and $20 taxi', multi: true),
  _x('en', 6, 'paid 0 USD'),
  _x('en', 7, 'obscene unsupported noise'),
];
