import Fastify, { type FastifyInstance, type FastifyRequest } from "fastify";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import fastifyJwt from "@fastify/jwt";
import rateLimit from "@fastify/rate-limit";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import { PrismaClient } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { config, allowedOrigins } from "./config.js";
import { createAuth, requireSnapshotRead, requireUser, signAccessToken } from "./auth.js";
import { buildAssistantSnapshot } from "./snapshot.js";
import { aiCaptureCommitSchema, aiCaptureEditSchema, aiCapturePreviewSchema, aiChatSchema, aiCreditAdminSchema, aiCreditFreezeSchema, canonicalMoneyCommitSchema, dateQuery, emailSchema, englishOnboardingSchema, feedbackSchema, invitationAcceptSchema, invitationCreateSchema, knowledgeCreateSchema, loginSchema, refreshSchema, registerSchema, resetPasswordSchema, snapshotQuery, syncBatchSchema, tenantSwitchSchema, tokenSchema, vaultImportCommitSchema } from "./schemas.js";
import { hashValue, publicAuditAction } from "./security.js";
import { moneySummary, salesSummary } from "./domain.js";
import { AiOrchestrator, CaptureService, KnowledgeService, aiToolDefinitions } from "./beta-services.js";
import { EmailService } from "./email.js";
import { VaultImportService } from "./vault-import.js";
import { AICreditService, InsufficientCreditsError, aiCreditPricing } from "./ai-credits.js";
import { aiModels, findAiModel } from "./ai-models.js";
import { EnglishOnboardingService } from "./english-onboarding.js";

type RecordValue = Record<string, unknown>;
const text = (row: RecordValue, key: string, fallback = "") => typeof row[key] === "string" ? row[key] as string : fallback;
const num = (row: RecordValue, key: string, fallback = 0) => typeof row[key] === "number" ? row[key] as number : Number(row[key] ?? fallback) || fallback;
const bool = (row: RecordValue, key: string, fallback = false) => typeof row[key] === "boolean" ? row[key] as boolean : row[key] === "true" ? true : row[key] === "false" ? false : fallback;
const nullableNumber = (row: RecordValue, key: string) => row[key] == null || row[key] === "" ? null : num(row, key);
const nullableInteger = (row: RecordValue, key: string) => {
  const value = nullableNumber(row, key);
  return value == null ? null : Math.round(value);
};
const clientId = (row: RecordValue) => text(row, "id") || text(row, "clientId") || randomUUID();
const createdAt = (row: RecordValue) => { const value = text(row, "createdAt"); return value ? new Date(value) : new Date(); };
const dateFilter = (from?: string, to?: string) => from || to ? { date: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {};
const callDateFilter = (from?: string, to?: string) => from || to ? { dateTime: { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) } } : {};

const audit = async (prisma: PrismaClient, request: FastifyRequest, action: string) => { await prisma.auditLog.create({ data: { userId: request.auth?.userId || null, action: publicAuditAction(action), method: request.method, route: request.routeOptions.url ?? request.url, requestId: request.id } }).catch(() => undefined); };

const writeBatch = async (prisma: PrismaClient, userId: string, body: ReturnType<typeof syncBatchSchema.parse>) => {
  const db = prisma as any;
  const batchId = body.batchId ?? randomUUID();
  let accepted = 0;
  const write = async (entity: string, row: RecordValue, data: RecordValue) => { const stableId = clientId(row); await db[entity].upsert({ where: { userId_clientId: { userId, clientId: stableId } }, create: { ...data, userId, clientId: stableId, createdAt: createdAt(row) }, update: data }); await prisma.syncEvent.upsert({ where: { userId_entity_clientId: { userId, entity, clientId: stableId } }, create: { userId, batchId, entity, clientId: stableId, operation: "upsert", payloadHash: hashValue(JSON.stringify(row)) }, update: { batchId, operation: "upsert", payloadHash: hashValue(JSON.stringify(row)), syncedAt: new Date() } }); accepted += 1; };
  for (const row of body.accounts) await write("account", row, { name: text(row, "name"), type: text(row, "type", "wallet"), currency: text(row, "currency", "UZS"), initialBalance: num(row, "initialBalance"), color: text(row, "color") || null });
  for (const row of body.categories) await write("category", row, { name: text(row, "name"), kind: text(row, "kind", "expense"), color: text(row, "color") || null, system: bool(row, "system") });
  for (const row of body.transactions) await write("transaction", row, { accountId: text(row, "accountId"), type: text(row, "type"), amount: num(row, "amount"), currency: text(row, "currency", "UZS"), date: text(row, "date"), counterparty: text(row, "counterparty") || null, categoryId: text(row, "categoryId") || null, purpose: text(row, "purpose") || null, paymentMethod: text(row, "paymentMethod") || null, transferToAccountId: text(row, "transferToAccountId") || null, recurring: bool(row, "recurring"), status: text(row, "status", "completed"), incomeSource: text(row, "incomeSource") || null, comment: text(row, "comment") || null, obligationId: text(row, "obligationId") || null, essential: bool(row, "essential") });
  for (const row of body.obligations) await write("obligation", row, { name: text(row, "name"), totalAmount: num(row, "totalAmount"), paidAmount: num(row, "paidAmount"), currency: text(row, "currency", "UZS"), dueDate: text(row, "dueDate"), recurrence: text(row, "recurrence", "once"), comment: text(row, "comment") || null, status: text(row, "status", "active") });
  for (const row of body.englishProgress) await write("englishProgress", row, { date: text(row, "date"), overallProgress: num(row, "overallProgress"), completedDays: Math.round(num(row, "completedDays")), activeDay: Math.round(num(row, "activeDay")), streak: Math.round(num(row, "streak")), studyMinutes: Math.round(num(row, "studyMinutes")), payload: row.payload ?? undefined });
  for (const row of body.leads) await write("lead", row, { companyName: text(row, "companyName"), contactName: text(row, "contactName") || null, position: text(row, "position") || null, phone: text(row, "phone") || null, telegram: text(row, "telegram") || null, city: text(row, "city") || null, niche: text(row, "niche") || null, source: text(row, "source", "other"), companyUrl: text(row, "companyUrl") || null, comment: text(row, "comment") || null, status: text(row, "status", "new") });
  for (const row of body.calls) await write("callActivity", row, { leadId: text(row, "leadId") || text(row, "clientId"), attemptNumber: Math.round(num(row, "attemptNumber", 1)), dateTime: new Date(text(row, "dateTime") || new Date().toISOString()), result: text(row, "result", "no_answer"), whatSaid: text(row, "whatSaid") || null, problem: text(row, "problem") || null, offered: text(row, "offered") || null, objection: text(row, "objection") || null, nextStep: text(row, "nextStep") || null, nextContactDate: text(row, "nextContactDate") || null, comment: text(row, "comment") || null });
  for (const row of body.offers) await write("offer", row, { leadId: text(row, "leadId") || text(row, "clientId"), serviceName: text(row, "serviceName") || text(row, "serviceId", "Другое"), taskDescription: text(row, "taskDescription") || null, amount: num(row, "amount"), currency: text(row, "currency", "UZS"), probability: Math.max(0, Math.min(100, Math.round(num(row, "probability")))), decisionDate: text(row, "decisionDate") || null, status: text(row, "status", "draft"), proposalUrl: text(row, "proposalUrl") || null, comment: text(row, "comment") || null });
  for (const row of body.followUps) await write("followUp", row, { leadId: text(row, "leadId") || text(row, "clientId"), date: text(row, "date"), reason: text(row, "reason"), lastResult: text(row, "lastResult") || null, nextStep: text(row, "nextStep") || null, status: text(row, "status", "future"), note: text(row, "note") || null });
  for (const row of body.dailyGoals) await write("dailyGoal", row, { date: text(row, "date"), kind: text(row, "kind", "calls"), target: Math.round(num(row, "target")), achieved: Math.round(num(row, "achieved")) });
  for (const row of body.sportMeasurements) await write("sportMeasurement", row, { date: text(row, "date"), weightKg: nullableNumber(row, "weightKg"), waistCm: nullableNumber(row, "waistCm"), abdomenCm: nullableNumber(row, "abdomenCm"), chestCm: nullableNumber(row, "chestCm"), bicepsLeftCm: nullableNumber(row, "bicepsLeftCm"), bicepsRightCm: nullableNumber(row, "bicepsRightCm"), thighLeftCm: nullableNumber(row, "thighLeftCm"), thighRightCm: nullableNumber(row, "thighRightCm"), bodyFatPercent: nullableNumber(row, "bodyFatPercent"), comment: text(row, "comment") || null });
  for (const row of body.workoutSessions) await write("workoutSession", row, { roadmapDayNumber: nullableInteger(row, "roadmapDayNumber"), date: text(row, "date"), workoutType: text(row, "workoutType", "gym"), workoutTemplate: text(row, "workoutTemplate") || null, startedAt: new Date(text(row, "startedAt") || new Date().toISOString()), finishedAt: text(row, "finishedAt") ? new Date(text(row, "finishedAt")) : null, durationMinutes: nullableInteger(row, "durationMinutes"), planned: bool(row, "planned"), completed: bool(row, "completed"), perceivedDifficulty: nullableInteger(row, "perceivedDifficulty"), energyBefore: nullableInteger(row, "energyBefore"), notes: text(row, "notes") || null });
  for (const row of body.workoutExercises) await write("workoutExercise", row, { workoutSessionClientId: text(row, "workoutSessionClientId"), exerciseId: text(row, "exerciseId") || null, nameSnapshot: text(row, "nameSnapshot"), primaryMuscleSnapshot: text(row, "primaryMuscleSnapshot"), targetSets: Math.round(num(row, "targetSets", 3)), targetRepRange: text(row, "targetRepRange"), completed: bool(row, "completed"), notes: text(row, "notes") || null });
  for (const row of body.exerciseSets) await write("exerciseSet", row, { workoutExerciseClientId: text(row, "workoutExerciseClientId"), setNumber: Math.round(num(row, "setNumber", 1)), weight: num(row, "weight"), repetitions: Math.round(num(row, "repetitions")), rpe: nullableInteger(row, "rpe"), rir: nullableInteger(row, "rir"), completed: bool(row, "completed"), warmup: bool(row, "warmup") });
  for (const row of body.basketballSessions) await write("basketballSession", row, { date: text(row, "date"), durationMinutes: Math.round(num(row, "durationMinutes")), format: text(row, "format", "casual"), intensity: Math.round(num(row, "intensity")), gamesPlayed: Math.round(num(row, "gamesPlayed")), kneeDiscomfort: Math.round(num(row, "kneeDiscomfort")), ankleDiscomfort: Math.round(num(row, "ankleDiscomfort")), notes: text(row, "notes") || null });
  for (const row of body.recoveryCheckIns) await write("recoveryCheckIn", row, { date: text(row, "date"), sleepHours: num(row, "sleepHours"), sleepQuality: Math.round(num(row, "sleepQuality")), energy: Math.round(num(row, "energy")), muscleSoreness: Math.round(num(row, "muscleSoreness")), jointPain: Math.round(num(row, "jointPain")), stress: Math.round(num(row, "stress")), motivation: Math.round(num(row, "motivation")), comment: text(row, "comment") || null });
  for (const row of body.sportCheckpoints) await write("sportCheckpoint", row, { dayNumber: Math.round(num(row, "dayNumber")), date: text(row, "date"), label: text(row, "label"), notes: text(row, "notes") || null, completed: bool(row, "completed") });
  for (const row of body.sportRoadmapDays) await write("sportRoadmapProgress", row, { dayNumber: Math.round(num(row, "dayNumber")), date: text(row, "date"), phase: Math.round(num(row, "phase")), plannedActivity: text(row, "plannedActivity"), workoutTemplate: text(row, "workoutTemplate") || null, status: text(row, "status", "available"), skipReason: text(row, "skipReason") || null });
  return { batchId, accepted, syncedAt: new Date().toISOString() };
};

export async function buildApp(prisma = new PrismaClient()) {
  const app = Fastify({ logger: false, requestIdHeader: "x-request-id" });
  await app.register(helmet);
  await app.register(cors, { origin: (origin, callback) => { if (!origin || allowedOrigins.includes(origin)) callback(null, true); else callback(new Error("origin_not_allowed"), false); } });
  await app.register(rateLimit, { max: config.RATE_LIMIT_MAX, timeWindow: config.RATE_LIMIT_WINDOW });
  app.addContentTypeParser("application/zip", { parseAs: "buffer", bodyLimit: config.KNOWLEDGE_MAX_ARCHIVE_BYTES }, (_request, body, done) => done(null, body));
  await app.register(fastifyJwt, { secret: config.JWT_SECRET });
  await app.register(swagger, { openapi: { info: { title: "Personal Tracker API", version: "1.0.0", description: "Local-first sync and read-only assistant snapshot API." }, servers: [{ url: "/" }], security: [{ bearerAuth: [] }], components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer" } } } } });
  await app.register(swaggerUi, { routePrefix: "/docs" });
  const auth = createAuth(prisma);
  const capture = new CaptureService(prisma);
  const knowledge = new KnowledgeService(prisma);
  const ai = new AiOrchestrator(prisma);
  const englishOnboarding = new EnglishOnboardingService();
  const email = new EmailService();
  const vault = new VaultImportService(prisma);
  const credits = new AICreditService(prisma);
  const isBetaOperator = async (request: FastifyRequest) => {
    const user = request.auth ? await prisma.user.findUnique({ where: { id: request.auth.userId }, select: { normalizedEmail: true } }) : null;
    return user?.normalizedEmail === config.ADMIN_EMAIL.trim().toLowerCase();
  };
  app.get("/health", async () => ({ status: "ok", service: "personal-tracker-api", version: "1.0.0" }));
  app.get("/ready", async (_request, reply) => { try { await prisma.$queryRaw`SELECT 1`; return { status: "ready" }; } catch { return reply.code(503).send({ status: "not_ready" }); } });
  app.post("/api/auth/register", { schema: { operationId: "register", tags: ["Auth"] } }, async (request, reply) => { if (config.BETA_REGISTRATION_ENABLED === "false") return reply.code(503).send({ error: "registration_disabled" }); const parsed = registerSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); if (parsed.data.consent.documentVersion !== config.REGISTRATION_CONSENT_VERSION) return reply.code(400).send({ error: "consent_version_invalid", requiredVersion: config.REGISTRATION_CONSENT_VERSION }); const result = await auth.register(parsed.data.email, parsed.data.password, parsed.data.displayName, parsed.data.consent); if (result.conflict) return reply.code(409).send({ error: "email_already_registered" }); await credits.ensureWallet({ userId: result.userId, tenantId: result.tenantId }, true); if (config.REQUIRE_EMAIL_VERIFICATION === "true") { const token = await auth.createVerification(result.userId); const delivery = await email.sendVerification(result.email, result.displayName, token); await prisma.betaAuditEvent.create({ data: { userId: result.userId, tenantId: result.tenantId, eventType: "auth.verification_requested", success: delivery.status !== "FAILED", correlationId: request.id } }); return reply.code(201).send({ userId: result.userId, tenantId: result.tenantId, verificationRequired: true }); } return reply.code(201).send({ accessToken: signAccessToken(app, result.userId, result.tenantId), userId: result.userId, tenantId: result.tenantId, expiresIn: 900 }); });
  app.post("/api/auth/login", { schema: { operationId: "login", tags: ["Auth"] } }, async (request, reply) => { if (config.API_ENABLED === "false") return reply.code(503).send({ error: "api_disabled" }); const parsed = loginSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const session = await auth.login(parsed.data.email, parsed.data.password); if (!session) return reply.code(401).send({ error: "invalid_credentials" }); return { accessToken: signAccessToken(app, session.userId, session.tenantId), refreshToken: session.refreshToken, expiresIn: 900, tenantId: session.tenantId }; });
  app.post("/api/auth/refresh", { schema: { operationId: "refreshSession", tags: ["Auth"] } }, async (request, reply) => { const parsed = refreshSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const session = await auth.refresh(parsed.data.refreshToken); if (!session) return reply.code(401).send({ error: "invalid_refresh_token" }); return { accessToken: signAccessToken(app, session.userId, session.tenantId), refreshToken: session.refreshToken, expiresIn: 900, tenantId: session.tenantId }; });
  // Compatibility aliases for existing mobile clients.
  app.post("/api/v1/auth/login", async (_request, reply) => reply.redirect("/api/auth/login", 307));
  app.post("/api/v1/auth/refresh", async (_request, reply) => reply.redirect("/api/auth/refresh", 307));
  app.post("/api/v1/auth/logout", { preHandler: requireUser }, async (request, reply) => { const parsed = refreshSchema.safeParse(request.body); if (parsed.success) await auth.logout(parsed.data.refreshToken); await audit(prisma, request, "auth.logout"); return reply.code(204).send(); });
  app.post("/api/auth/logout", { preHandler: requireUser, schema: { operationId: "logout", tags: ["Auth"] } }, async (request, reply) => { const parsed = refreshSchema.safeParse(request.body); if (parsed.success) await auth.logout(parsed.data.refreshToken); return reply.code(204).send(); });
  app.post("/api/auth/logout-all", { preHandler: requireUser, schema: { operationId: "logoutAll", tags: ["Auth"] } }, async (request, reply) => { await auth.logoutAll(request.auth!.userId); return reply.code(204).send(); });
  app.post("/api/auth/verify-email", { schema: { operationId: "verifyEmail", tags: ["Auth"] } }, async (request, reply) => { const parsed = tokenSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const user = await auth.verifyEmail(parsed.data.token); if (!user) return reply.code(400).send({ error: "invalid_or_expired_verification" }); await prisma.betaAuditEvent.create({ data: { userId: user.id, eventType: "auth.email_verified", correlationId: request.id } }); return reply.code(204).send(); });
  app.get("/verify-email", { schema: { operationId: "verifyEmailFromLink", tags: ["Auth"] } }, async (request, reply) => {
    const token = (request.query as { token?: string }).token;
    const valid = typeof token === "string" && tokenSchema.safeParse({ token }).success;
    if (!valid) return reply.type("text/html").code(400).send("<!doctype html><meta charset=\"utf-8\"><title>Codev-Tim</title><h1>Ссылка недействительна</h1><p>Запросите новое письмо подтверждения.</p>");
    const user = await auth.verifyEmail(token);
    if (!user) return reply.type("text/html").code(400).send("<!doctype html><meta charset=\"utf-8\"><title>Codev-Tim</title><h1>Ссылка устарела</h1><p>Запросите новое письмо подтверждения.</p>");
    await prisma.betaAuditEvent.create({ data: { userId: user.id, eventType: "auth.email_verified", correlationId: request.id } });
    return reply.type("text/html").send("<!doctype html><meta charset=\"utf-8\"><title>Codev-Tim</title><style>body{font-family:system-ui;background:#050505;color:#edeff2;display:grid;place-items:center;min-height:100vh}main{max-width:520px;padding:32px;text-align:center}h1{color:#f0b429}</style><main><h1>Email подтверждён</h1><p>Теперь можно вернуться в приложение Codev-Tim и войти.</p></main>");
  });
  app.post("/api/auth/resend-verification", { config: { rateLimit: { max: 3, timeWindow: "1 hour" } }, schema: { operationId: "resendVerification", tags: ["Auth"] } }, async (request, reply) => { const parsed = emailSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const pending = await prisma.user.findFirst({ where: { normalizedEmail: parsed.data.email.trim().toLowerCase(), status: "PENDING" }, select: { id: true, email: true, displayName: true } }); if (pending) { const token = await auth.createVerification(pending.id); await email.sendVerification(pending.email, pending.displayName, token); } return reply.code(202).send({ message: "If the account is pending, a new verification message has been sent." }); });
  app.post("/api/auth/forgot-password", { config: { rateLimit: { max: config.RESET_RATE_LIMIT_MAX, timeWindow: "1 hour" } }, schema: { operationId: "forgotPassword", tags: ["Auth"] } }, async (request, reply) => { const parsed = emailSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const reset = await auth.createPasswordReset(parsed.data.email.trim().toLowerCase()); if (reset) { const delivery = await email.sendPasswordReset(reset.email, reset.displayName, reset.token); await prisma.betaAuditEvent.create({ data: { userId: reset.id, eventType: "auth.password_reset_requested", success: delivery.status !== "FAILED", correlationId: request.id } }); } return reply.code(202).send({ message: "If an account exists, password reset instructions have been sent." }); });
  app.post("/api/auth/reset-password", { config: { rateLimit: { max: config.RESET_RATE_LIMIT_MAX, timeWindow: "1 hour" } }, schema: { operationId: "resetPassword", tags: ["Auth"] } }, async (request, reply) => { const parsed = resetPasswordSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const changed = await auth.resetPassword(parsed.data.token, parsed.data.password); if (!changed) return reply.code(400).send({ error: "invalid_or_expired_reset" }); await prisma.betaAuditEvent.create({ data: { eventType: "auth.password_reset", correlationId: request.id } }); return reply.code(204).send(); });
  app.get("/api/auth/me", { preHandler: requireUser, schema: { operationId: "getCurrentUser", tags: ["Auth"] } }, async (request) => { const user = await prisma.user.findUnique({ where: { id: request.auth!.userId }, select: { id: true, email: true, displayName: true, status: true, emailVerifiedAt: true } }); return { user, activeTenantId: request.auth!.tenantId }; });
  app.get("/api/tenants", { preHandler: requireUser, schema: { operationId: "listTenants", tags: ["Tenants"] } }, async (request) => prisma.tenantMembership.findMany({ where: { userId: request.auth!.userId, status: "ACTIVE" }, include: { tenant: true }, orderBy: { createdAt: "asc" } }));
  app.post("/api/tenants/switch", { preHandler: requireUser, schema: { operationId: "switchTenant", tags: ["Tenants"] } }, async (request, reply) => { const parsed = tenantSwitchSchema.safeParse(request.body); if (!parsed.success || !(await auth.hasMembership(request.auth!.userId, parsed.data.tenantId))) return reply.code(403).send({ error: "tenant_access_denied" }); return { accessToken: signAccessToken(app, request.auth!.userId, parsed.data.tenantId), tenantId: parsed.data.tenantId, expiresIn: 900 }; });
  app.get("/api/v1/auth/check", { preHandler: requireUser }, async (request) => ({ authenticated: true, userId: request.auth?.userId, tenantId: request.auth?.tenantId, role: request.auth?.role }));
  const syncHandler = async (request: FastifyRequest, reply: any) => { const parsed = syncBatchSchema.safeParse(request.body); if (!parsed.success || !request.auth?.userId) return reply.code(400).send({ error: "invalid_batch" }); const result = await writeBatch(prisma, request.auth.userId, parsed.data); await audit(prisma, request, "sync.batch"); return result; };
  app.post("/api/v1/sync", { preHandler: requireUser }, syncHandler);
  app.post("/api/v1/sync/batch", { preHandler: requireUser }, syncHandler);
  app.post("/api/v2/capture/commits", { preHandler: requireUser }, async (request, reply) => {
    const parsed = canonicalMoneyCommitSchema.safeParse(request.body);
    if (!parsed.success || !request.auth?.userId) return reply.code(400).send({ error: "invalid_canonical_commit" });
    const input = parsed.data;
    const accountAllowed = input.accountId === "__unassigned__" || await prisma.account.findFirst({ where: { userId: request.auth.userId, clientId: input.accountId }, select: { clientId: true } });
    if (!accountAllowed) return reply.code(422).send({ error: "account_not_owned" });
    if (input.categoryId && input.categoryId !== "__unclassified__") {
      const categoryAllowed = await prisma.category.findFirst({ where: { userId: request.auth.userId, clientId: input.categoryId }, select: { clientId: true } });
      if (!categoryAllowed) return reply.code(422).send({ error: "category_not_owned" });
    }
    const scale = input.currency === "UZS" ? 0 : input.currency === "USD" || input.currency === "EUR" ? 2 : -1;
    if (scale < 0) return reply.code(400).send({ error: "unsupported_currency" });
    const amount = Number(input.exactMinorUnits) / 10 ** scale;
    if (!Number.isSafeInteger(Number(input.exactMinorUnits)) || !Number.isFinite(amount)) return reply.code(400).send({ error: "amount_not_representable" });
    const result = await prisma.$transaction(async (db) => {
      const existing = await db.canonicalMoneyCommit.findUnique({ where: { userId_captureId: { userId: request.auth!.userId, captureId: input.captureId } } });
      if (existing) return { status: "already_committed", captureId: existing.captureId, transactionId: existing.captureId };
      await db.transaction.upsert({
        where: { userId_clientId: { userId: request.auth!.userId, clientId: input.captureId } },
        create: { userId: request.auth!.userId, clientId: input.captureId, accountId: input.accountId, type: input.direction, amount, currency: input.currency, date: input.date, categoryId: input.categoryId ?? null, purpose: input.description, paymentMethod: input.paymentMethod ?? null, status: "completed", essential: true },
        update: { accountId: input.accountId, type: input.direction, amount, currency: input.currency, date: input.date, categoryId: input.categoryId ?? null, purpose: input.description, paymentMethod: input.paymentMethod ?? null, status: "completed" },
      });
      await db.canonicalMoneyCommit.create({ data: { userId: request.auth!.userId, captureId: input.captureId, exactMinorUnits: input.exactMinorUnits, currency: input.currency, direction: input.direction, date: input.date, description: input.description, accountId: input.accountId, categoryId: input.categoryId ?? null, paymentMethod: input.paymentMethod ?? null, intentJson: input.intentJson as any } });
      return { status: "committed", captureId: input.captureId, transactionId: input.captureId };
    });
    await audit(prisma, request, "sync.canonical_money_commit");
    return result;
  });
  app.get("/api/v1/sync/status", { preHandler: requireUser }, async (request) => { const latest = request.auth?.userId ? await prisma.syncEvent.findFirst({ where: { userId: request.auth.userId }, orderBy: { syncedAt: "desc" } }) : null; return { apiEnabled: config.API_ENABLED === "true", lastSuccessfulSync: latest?.syncedAt ?? null, pending: 0 }; });
  app.get("/api/v1/transactions", { preHandler: requireUser }, async (request, reply) => { const parsed = dateQuery.safeParse(request.query); if (!parsed.success || !request.auth?.userId) return reply.code(400).send({ error: "invalid_query" }); return prisma.transaction.findMany({ where: { userId: request.auth.userId, ...dateFilter(parsed.data.from, parsed.data.to) }, orderBy: { date: "desc" }, take: 500 }); });
  app.get("/api/v1/transactions/summary", { preHandler: requireUser }, async (request, reply) => { const parsed = dateQuery.safeParse(request.query); if (!parsed.success || !request.auth?.userId) return reply.code(400).send({ error: "invalid_query" }); const rows = await prisma.transaction.findMany({ where: { userId: request.auth.userId, ...dateFilter(parsed.data.from, parsed.data.to) } }); return moneySummary(rows); });
  app.get("/api/v1/accounts", { preHandler: requireUser }, async (request) => prisma.account.findMany({ where: { userId: request.auth?.userId }, orderBy: { createdAt: "asc" } }));
  app.get("/api/v1/categories", { preHandler: requireUser }, async (request) => prisma.category.findMany({ where: { userId: request.auth?.userId }, orderBy: { createdAt: "asc" } }));
  app.get("/api/v1/obligations", { preHandler: requireUser }, async (request) => prisma.obligation.findMany({ where: { userId: request.auth?.userId }, orderBy: { dueDate: "asc" } }));
  app.get("/api/v1/english/progress", { preHandler: requireUser }, async (request) => prisma.englishProgress.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" }, take: 90 }));
  app.get("/api/v1/english/summary", { preHandler: requireUser }, async (request) => { const latest = await prisma.englishProgress.findFirst({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" } }); return { progress: latest?.overallProgress ?? 0, completedDays: latest?.completedDays ?? 0, activeDay: latest?.activeDay ?? 0, streak: latest?.streak ?? 0, studyMinutes: latest?.studyMinutes ?? 0 }; });
  app.get("/api/v1/leads", { preHandler: requireUser }, async (request) => prisma.lead.findMany({ where: { userId: request.auth?.userId }, orderBy: { createdAt: "desc" }, take: 500 }));
  app.get("/api/v1/calls", { preHandler: requireUser }, async (request, reply) => { const parsed = dateQuery.safeParse(request.query); if (!parsed.success) return reply.code(400).send({ error: "invalid_query" }); return prisma.callActivity.findMany({ where: { userId: request.auth?.userId, ...callDateFilter(parsed.data.from, parsed.data.to) }, orderBy: { dateTime: "desc" }, take: 1000 }); });
  app.get("/api/v1/followups", { preHandler: requireUser }, async (request) => prisma.followUp.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "asc" }, take: 500 }));
  app.get("/api/v1/offers", { preHandler: requireUser }, async (request) => prisma.offer.findMany({ where: { userId: request.auth?.userId }, orderBy: { updatedAt: "desc" }, take: 500 }));
  app.get("/api/v1/sales/summary", { preHandler: requireUser }, async (request, reply) => { const parsed = dateQuery.safeParse(request.query); if (!parsed.success) return reply.code(400).send({ error: "invalid_query" }); const [calls, offers] = await Promise.all([prisma.callActivity.findMany({ where: { userId: request.auth?.userId, ...callDateFilter(parsed.data.from, parsed.data.to) } }), prisma.offer.findMany({ where: { userId: request.auth?.userId } })]); return salesSummary(calls, offers); });
  app.get("/api/v1/sport/measurements", { preHandler: requireUser }, async (request) => prisma.sportMeasurement.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" }, take: 500 }));
  app.get("/api/v1/sport/workouts", { preHandler: requireUser }, async (request) => prisma.workoutSession.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" }, take: 500 }));
  app.get("/api/v1/sport/basketball", { preHandler: requireUser }, async (request) => prisma.basketballSession.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" }, take: 500 }));
  app.get("/api/v1/sport/recovery", { preHandler: requireUser }, async (request) => prisma.recoveryCheckIn.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "desc" }, take: 180 }));
  app.get("/api/v1/sport/checkpoints", { preHandler: requireUser }, async (request) => prisma.sportCheckpoint.findMany({ where: { userId: request.auth?.userId }, orderBy: { date: "asc" } }));
  app.get("/api/v1/sport/roadmap", { preHandler: requireUser }, async (request) => prisma.sportRoadmapProgress.findMany({ where: { userId: request.auth?.userId }, orderBy: { dayNumber: "asc" } }));
  app.get("/api/v1/dashboard/summary", { preHandler: requireUser }, async (request, reply) => { const parsed = dateQuery.safeParse(request.query); if (!parsed.success || !request.auth?.userId) return reply.code(400).send({ error: "invalid_query" }); return buildAssistantSnapshot(prisma, request.auth.userId, { ...parsed.data }); });
  app.get("/api/v1/assistant/snapshot", { preHandler: requireSnapshotRead }, async (request, reply) => { const parsed = snapshotQuery.safeParse(request.query); if (!parsed.success) return reply.code(400).send({ error: "invalid_query" }); const userId = request.auth?.userId || (await prisma.user.findFirst({ orderBy: { createdAt: "asc" } }))?.id; if (!userId) return reply.code(404).send({ error: "snapshot_user_not_found" }); await audit(prisma, request, "assistant.snapshot"); return buildAssistantSnapshot(prisma, userId, parsed.data); });
  app.get("/api/v1/export/assistant.json", { preHandler: requireSnapshotRead }, async (request, reply) => { const parsed = snapshotQuery.safeParse(request.query); if (!parsed.success) return reply.code(400).send({ error: "invalid_query" }); const userId = request.auth?.userId || (await prisma.user.findFirst({ orderBy: { createdAt: "asc" } }))?.id; if (!userId) return reply.code(404).send({ error: "snapshot_user_not_found" }); const payload = await buildAssistantSnapshot(prisma, userId, parsed.data); await audit(prisma, request, "assistant.export"); return reply.header("Content-Disposition", "attachment; filename=personal-tracker-assistant-snapshot.json").send(payload); });
  app.post("/api/beta/invitations", { preHandler: requireUser, schema: { operationId: "createBetaInvitation", tags: ["Beta administration"] } }, async (request, reply) => {
    if (config.BETA_INVITATIONS_ENABLED === "false") return reply.code(503).send({ error: "invitations_disabled" });
    const parsed = invitationCreateSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" });
    const membership = await prisma.tenantMembership.findFirst({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, role: "OWNER", status: "ACTIVE" } });
    if (!membership) return reply.code(403).send({ error: "owner_required" });
    const token = `${randomUUID()}${randomUUID()}`;
    const expiresAt = new Date(Date.now() + parsed.data.expiresInDays * 86400000);
    const invitation = await prisma.invitation.create({ data: { tenantId: request.auth!.tenantId, email: parsed.data.email.trim().toLowerCase(), normalizedEmail: parsed.data.email.trim().toLowerCase(), role: parsed.data.role, tokenHash: hashValue(token), expiresAt, invitedByUserId: request.auth!.userId } });
    const inviter = await prisma.user.findUnique({ where: { id: request.auth!.userId }, select: { displayName: true } });
    const delivery = await email.sendInvitation(invitation.email, inviter?.displayName ?? "Personal Tracker owner", token, expiresAt);
    await prisma.invitation.update({ where: { id: invitation.id }, data: { deliveryStatus: delivery.status === "FAILED" ? "FAILED" : "SENT", lastSentAt: new Date(), deliveryAttempts: 1 } });
    await prisma.betaAuditEvent.create({ data: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "invitation.create", entityType: "invitation", entityId: invitation.id, correlationId: request.id } });
    return { id: invitation.id, email: invitation.email, expiresAt: invitation.expiresAt, deliveryStatus: delivery.status, ...(config.NODE_ENV === "production" ? {} : { token }) };
  });
  app.get("/api/beta/invitations", { preHandler: requireUser, schema: { operationId: "listBetaInvitations", tags: ["Beta administration"] } }, async (request, reply) => {
    const owner = await prisma.tenantMembership.findFirst({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, role: "OWNER", status: "ACTIVE" } });
    if (!owner) return reply.code(403).send({ error: "owner_required" });
    return prisma.invitation.findMany({ where: { tenantId: request.auth!.tenantId }, select: { id: true, email: true, role: true, expiresAt: true, acceptedAt: true, status: true, deliveryStatus: true, deliveryAttempts: true, lastSentAt: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 50 });
  });
  app.post("/api/beta/invitations/:id/resend", { preHandler: requireUser, config: { rateLimit: { max: config.INVITATION_RESEND_RATE_LIMIT_MAX, timeWindow: "1 hour" } }, schema: { operationId: "resendBetaInvitation", tags: ["Beta administration"] } }, async (request, reply) => {
    const owner = await prisma.tenantMembership.findFirst({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, role: "OWNER", status: "ACTIVE" } }); if (!owner) return reply.code(403).send({ error: "owner_required" });
    const invitation = await prisma.invitation.findFirst({ where: { id: (request.params as { id: string }).id, tenantId: request.auth!.tenantId, status: "PENDING", expiresAt: { gt: new Date() } } }); if (!invitation) return reply.code(404).send({ error: "invitation_not_found" });
    const token = `${randomUUID()}${randomUUID()}`; const inviter = await prisma.user.findUnique({ where: { id: request.auth!.userId }, select: { displayName: true } }); const delivery = await email.sendInvitation(invitation.email, inviter?.displayName ?? "Personal Tracker owner", token, invitation.expiresAt);
    await prisma.invitation.update({ where: { id: invitation.id }, data: { tokenHash: hashValue(token), deliveryStatus: delivery.status === "FAILED" ? "FAILED" : "SENT", deliveryAttempts: { increment: 1 }, lastSentAt: new Date() } });
    return { id: invitation.id, deliveryStatus: delivery.status, ...(config.NODE_ENV === "production" ? {} : { token }) };
  });
  app.post("/api/beta/invitations/:id/revoke", { preHandler: requireUser, schema: { operationId: "revokeBetaInvitation", tags: ["Beta administration"] } }, async (request, reply) => {
    const owner = await prisma.tenantMembership.findFirst({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, role: "OWNER", status: "ACTIVE" } });
    if (!owner) return reply.code(403).send({ error: "owner_required" });
    const invitation = await prisma.invitation.findFirst({ where: { id: (request.params as { id: string }).id, tenantId: request.auth!.tenantId, status: "PENDING" } });
    if (!invitation) return reply.code(404).send({ error: "invitation_not_found" });
    await prisma.invitation.update({ where: { id: invitation.id }, data: { status: "REVOKED" } });
    return reply.code(204).send();
  });
  app.post("/api/invitations/accept", { preHandler: requireUser, schema: { operationId: "acceptInvitation", tags: ["Invitations"] } }, async (request, reply) => {
    const parsed = invitationAcceptSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" });
    const invitation = await prisma.invitation.findUnique({ where: { tokenHash: hashValue(parsed.data.token) }, include: { tenant: { select: { type: true } } } });
    if (!invitation || invitation.status !== "PENDING" || invitation.expiresAt <= new Date()) return reply.code(400).send({ error: "invalid_or_expired_invitation" });
    const user = await prisma.user.findUnique({ where: { id: request.auth!.userId }, select: { normalizedEmail: true } });
    if (!user || user.normalizedEmail !== invitation.normalizedEmail) return reply.code(403).send({ error: "invitation_email_mismatch" });
    const changes = [prisma.invitation.update({ where: { id: invitation.id }, data: { status: "ACCEPTED", acceptedAt: new Date() } })];
    // A personal-tenant invitation is an allow-list ticket for closed beta;
    // it must never merge a tester into the owner's private data space.
    if (invitation.tenant.type === "TEAM") changes.push(prisma.tenantMembership.upsert({ where: { tenantId_userId: { tenantId: invitation.tenantId, userId: request.auth!.userId } }, create: { tenantId: invitation.tenantId, userId: request.auth!.userId, role: invitation.role }, update: { status: "ACTIVE", role: invitation.role } }) as any);
    await prisma.$transaction(changes);
    const activeTenantId = invitation.tenant.type === "TEAM" ? invitation.tenantId : request.auth!.tenantId;
    return { tenantId: activeTenantId, accessToken: signAccessToken(app, request.auth!.userId, activeTenantId), expiresIn: 900 };
  });
  app.get("/api/knowledge/documents", { preHandler: requireUser, schema: { operationId: "listKnowledgeDocuments", tags: ["Knowledge"] } }, async (request) => knowledge.list(request.auth!, typeof (request.query as { q?: string }).q === "string" ? (request.query as { q: string }).q : undefined));
  app.get("/api/knowledge/documents/:id", { preHandler: requireUser, schema: { operationId: "getKnowledgeDocument", tags: ["Knowledge"] } }, async (request, reply) => { const document = await knowledge.get(request.auth!, (request.params as { id: string }).id); return document ?? reply.code(404).send({ error: "knowledge_document_not_found" }); });
  app.post("/api/knowledge/documents", { preHandler: requireUser, schema: { operationId: "saveKnowledgeDocument", tags: ["Knowledge"] } }, async (request, reply) => { const parsed = knowledgeCreateSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); try { const result = await knowledge.save(request.auth!, parsed.data); if (result.conflict) return reply.code(409).send({ error: "knowledge_conflict", document: result.document }); return reply.code(201).send(result.document); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : "knowledge_failed" }); } });
  app.get("/api/knowledge/export", { preHandler: requireUser, schema: { operationId: "exportKnowledgeVault", tags: ["Knowledge"] } }, async (request) => { const documents = await knowledge.list(request.auth!); await prisma.betaAuditEvent.create({ data: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "knowledge.export", correlationId: request.id } }); return { format: "obsidian-compatible-markdown", documents }; });
  app.post("/api/knowledge/vault/import/dry-run", { preHandler: requireUser, schema: { operationId: "dryRunKnowledgeVaultImport", tags: ["Knowledge"] } }, async (request, reply) => { if (config.BETA_VAULT_IMPORT_ENABLED === "false") return reply.code(503).send({ error: "vault_import_disabled" }); try { const result = await vault.dryRun(request.auth!, request.body as Buffer); await prisma.betaAuditEvent.create({ data: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "knowledge.vault_dry_run", entityId: result.importSessionId, correlationId: request.id } }); return result; } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : "vault_dry_run_failed" }); } });
  app.post("/api/knowledge/vault/import/commit", { preHandler: requireUser, schema: { operationId: "commitKnowledgeVaultImport", tags: ["Knowledge"] } }, async (request, reply) => { if (config.BETA_VAULT_IMPORT_ENABLED === "false") return reply.code(503).send({ error: "vault_import_disabled" }); const parsed = vaultImportCommitSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); try { const result = await vault.commit(request.auth!, parsed.data); await prisma.betaAuditEvent.create({ data: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "knowledge.vault_commit", entityId: result.importSessionId, correlationId: request.id } }); return result; } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : "vault_commit_failed" }); } });
  app.get("/api/ai/credits/balance", { preHandler: requireUser, schema: { operationId: "getAiCreditBalance", tags: ["AI credits"] } }, async (request) => credits.balance(request.auth!));
  app.get("/api/ai/status", { preHandler: requireUser, schema: { operationId: "getAiStatus", tags: ["AI"] } }, async (request) => {
    const dayStart = new Date();
    dayStart.setUTCHours(0, 0, 0, 0);
    const usedToday = await prisma.betaAuditEvent.count({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "ai.request", createdAt: { gte: dayStart } } });
    const balance = await credits.balance(request.auth!);
    const configured = config.OPENAI_ENABLED === "true" && Boolean(config.OPENAI_API_KEY);
    return { configured, provider: configured ? "openai" : "local_fallback", model: config.OPENAI_CHAT_MODEL ?? config.OPENAI_MODEL, models: aiModels, dailyLimit: config.OPENAI_DAILY_USER_BUDGET, usedToday, remainingToday: Math.max(0, config.OPENAI_DAILY_USER_BUDGET - usedToday), creditsEnabled: config.AI_CREDITS_ENABLED === "true", ...balance };
  });
  app.get("/api/ai/models", { preHandler: requireUser, schema: { operationId: "getAiModels", tags: ["AI"] } }, async () => ({ models: aiModels, defaultModel: findAiModel().id }));
  app.get("/api/ai/credits/history", { preHandler: requireUser, schema: { operationId: "getAiCreditHistory", tags: ["AI credits"] } }, async (request) => credits.history(request.auth!));
  app.get("/api/ai/credits/packages", { preHandler: requireUser, schema: { operationId: "getAiCreditPackages", tags: ["AI credits"] } }, async () => credits.packages());
  app.get("/api/ai/credits/pricing", { preHandler: requireUser, schema: { operationId: "getAiCreditPricing", tags: ["AI credits"] } }, async () => aiCreditPricing);
  app.post("/api/admin/ai-credits/grant", { preHandler: requireUser, schema: { operationId: "grantAiCredits", tags: ["Beta administration"] } }, async (request, reply) => { if (!(await isBetaOperator(request))) return reply.code(403).send({ error: "beta_operator_required" }); const parsed = aiCreditAdminSchema.safeParse(request.body); if (!parsed.success || !parsed.data.amount) return reply.code(400).send({ error: "invalid_request" }); const membership = await prisma.tenantMembership.findFirst({ where: { tenantId: parsed.data.tenantId, userId: parsed.data.userId, status: "ACTIVE" } }); if (!membership) return reply.code(404).send({ error: "wallet_subject_not_found" }); const result = await credits.grant(parsed.data, parsed.data.amount, parsed.data.reason, parsed.data.idempotencyKey); await prisma.betaAuditEvent.create({ data: { tenantId: parsed.data.tenantId, userId: request.auth!.userId, eventType: "ai_credit.grant", entityId: parsed.data.userId, correlationId: request.id, metadata: { amount: parsed.data.amount, reason: parsed.data.reason } } }); return result; });
  app.post("/api/admin/ai-credits/adjust", { preHandler: requireUser, schema: { operationId: "adjustAiCredits", tags: ["Beta administration"] } }, async (request, reply) => { if (!(await isBetaOperator(request))) return reply.code(403).send({ error: "beta_operator_required" }); const parsed = aiCreditAdminSchema.safeParse(request.body); if (!parsed.success || !parsed.data.amount) return reply.code(400).send({ error: "invalid_request" }); const membership = await prisma.tenantMembership.findFirst({ where: { tenantId: parsed.data.tenantId, userId: parsed.data.userId, status: "ACTIVE" } }); if (!membership) return reply.code(404).send({ error: "wallet_subject_not_found" }); const result = await credits.grant(parsed.data, parsed.data.amount, parsed.data.reason, parsed.data.idempotencyKey, "ADJUSTMENT"); await prisma.betaAuditEvent.create({ data: { tenantId: parsed.data.tenantId, userId: request.auth!.userId, eventType: "ai_credit.adjust", entityId: parsed.data.userId, correlationId: request.id } }); return result; });
  app.post("/api/admin/ai-credits/freeze", { preHandler: requireUser, schema: { operationId: "freezeAiCredits", tags: ["Beta administration"] } }, async (request, reply) => { if (!(await isBetaOperator(request))) return reply.code(403).send({ error: "beta_operator_required" }); const parsed = aiCreditFreezeSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const membership = await prisma.tenantMembership.findFirst({ where: { tenantId: parsed.data.tenantId, userId: parsed.data.userId, status: "ACTIVE" } }); if (!membership) return reply.code(404).send({ error: "wallet_subject_not_found" }); const result = await credits.freeze(parsed.data, parsed.data.status, parsed.data.reason, parsed.data.idempotencyKey); await prisma.betaAuditEvent.create({ data: { tenantId: parsed.data.tenantId, userId: request.auth!.userId, eventType: "ai_credit.freeze", entityId: parsed.data.userId, correlationId: request.id } }); return result; });
  app.post("/api/ai/capture/preview", { preHandler: requireUser, schema: { operationId: "createCapturePreview", tags: ["AI"] } }, async (request, reply) => { const parsed = aiCapturePreviewSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); let usage; try { usage = await credits.reserve(request.auth!, "capture_preview", request.id); const preview = await capture.preview({ ...request.auth!, requestId: request.id }, parsed.data.text, parsed.data.type); const charged = await credits.complete(request.auth!, usage.id, usage.creditsReserved); return { id: preview.id, type: preview.type, payload: preview.payload, expiresAt: preview.expiresAt, creditsCharged: charged.charged, creditBalance: charged.balance }; } catch (error) { if (usage) await credits.fail(request.auth!, usage.id, error instanceof Error ? error.message : "capture_failed"); if (error instanceof InsufficientCreditsError) return reply.code(402).send({ error: "AI_CREDITS_INSUFFICIENT", requiredCredits: error.requiredCredits, availableCredits: error.availableCredits, operationType: error.operationType }); return reply.code(409).send({ error: error instanceof Error ? error.message : "ai_capture_failed" }); } });
  app.post("/api/ai/capture/preview/:id/edit", { preHandler: requireUser, schema: { operationId: "editCapturePreview", tags: ["AI"] } }, async (request, reply) => { const parsed = aiCaptureEditSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); try { const preview = await capture.edit(request.auth!, (request.params as { id: string }).id, parsed.data.type, parsed.data.payload); return { id: preview.id, type: preview.type, payload: preview.payload, expiresAt: preview.expiresAt }; } catch (error) { return reply.code(404).send({ error: error instanceof Error ? error.message : "capture_preview_not_found" }); } });
  app.post("/api/ai/capture/commit", { preHandler: requireUser, schema: { operationId: "commitCapturePreview", tags: ["AI"] } }, async (request, reply) => { const parsed = aiCaptureCommitSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); try { return await capture.commit(request.auth!, parsed.data.previewId, parsed.data.confirmationId); } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : "capture_commit_failed" }); } });
  app.post("/api/ai/chat", { preHandler: requireUser, schema: { operationId: "chatWithAssistant", tags: ["AI"] } }, async (request, reply) => { const parsed = aiChatSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const model = findAiModel(parsed.data.model); const creditCost = config.OPENAI_ENABLED === "true" ? model.creditsPerChat : 0; let usage; try { usage = await credits.reserve(request.auth!, "chat", request.id, parsed.data.conversationId, creditCost); const result = await ai.chat({ ...request.auth!, requestId: request.id }, parsed.data.message, parsed.data.conversationId, model.id); const charged = await credits.complete(request.auth!, usage.id, usage.creditsReserved); return { ...result, creditsCharged: charged.charged, creditBalance: charged.balance }; } catch (error) { if (usage) await credits.fail(request.auth!, usage.id, error instanceof Error ? error.message : "chat_failed"); if (error instanceof InsufficientCreditsError) return reply.code(402).send({ error: "AI_CREDITS_INSUFFICIENT", requiredCredits: error.requiredCredits, availableCredits: error.availableCredits, operationType: "chat" }); return reply.code(429).send({ error: error instanceof Error ? error.message : "ai_request_failed" }); } });
  app.post("/api/ai/english-onboarding", { preHandler: requireUser, schema: { operationId: "englishOnboardingTurn", tags: ["AI"] } }, async (request, reply) => { const parsed = englishOnboardingSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); let usage; try { usage = await credits.reserve(request.auth!, "english_onboarding", request.id); const result = await englishOnboarding.reply(parsed.data); const charged = await credits.complete(request.auth!, usage.id, usage.creditsReserved, { inputTokens: result.inputTokens, outputTokens: result.outputTokens }); return { reply: result.reply, facts: result.facts, missing: result.missing, ready: result.ready, creditsCharged: charged.charged, creditBalance: charged.balance, provider: "openai" }; } catch (error) { if (usage) await credits.fail(request.auth!, usage.id, error instanceof Error ? error.message : "english_onboarding_failed"); if (error instanceof InsufficientCreditsError) return reply.code(402).send({ error: "AI_CREDITS_INSUFFICIENT", requiredCredits: error.requiredCredits, availableCredits: error.availableCredits, operationType: error.operationType }); const code = error instanceof Error && error.message === "english_ai_unavailable" ? 503 : 429; return reply.code(code).send({ error: error instanceof Error ? error.message : "english_onboarding_failed" }); } });
  app.get("/api/ai/conversations", { preHandler: requireUser, schema: { operationId: "listAiConversations", tags: ["AI"] } }, async (request) => prisma.aiConversation.findMany({ where: { tenantId: request.auth!.tenantId, userId: request.auth!.userId }, select: { id: true, title: true, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 50 }));
  app.get("/api/ai/conversations/:id", { preHandler: requireUser, schema: { operationId: "getAiConversation", tags: ["AI"] } }, async (request, reply) => { const conversation = await prisma.aiConversation.findFirst({ where: { id: (request.params as { id: string }).id, tenantId: request.auth!.tenantId, userId: request.auth!.userId }, include: { messages: { orderBy: { createdAt: "asc" } } } }); return conversation ?? reply.code(404).send({ error: "conversation_not_found" }); });
  app.get("/api/ai/memory/candidates", { preHandler: requireUser, schema: { operationId: "listMemoryCandidates", tags: ["AI"] } }, async (request) => prisma.aiMemory.findMany({ where: { tenantId: request.auth!.tenantId, createdByUserId: request.auth!.userId, status: "CANDIDATE" }, orderBy: { createdAt: "desc" } }));
  app.post("/api/ai/memory/candidates/:id/approve", { preHandler: requireUser, schema: { operationId: "approveMemoryCandidate", tags: ["AI"] } }, async (request, reply) => { try { return await ai.approveMemory(request.auth!, (request.params as { id: string }).id, true); } catch { return reply.code(404).send({ error: "memory_candidate_not_found" }); } });
  app.post("/api/ai/memory/candidates/:id/reject", { preHandler: requireUser, schema: { operationId: "rejectMemoryCandidate", tags: ["AI"] } }, async (request, reply) => { try { return await ai.approveMemory(request.auth!, (request.params as { id: string }).id, false); } catch { return reply.code(404).send({ error: "memory_candidate_not_found" }); } });
  app.get("/api/ai/tools", { preHandler: requireUser, schema: { operationId: "listSafeAiTools", tags: ["AI"] } }, async () => ({ tools: aiToolDefinitions }));
  app.post("/api/feedback", { preHandler: requireUser, schema: { operationId: "submitBetaFeedback", tags: ["Feedback"] } }, async (request, reply) => { const parsed = feedbackSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "invalid_request" }); const event = await prisma.betaAuditEvent.create({ data: { tenantId: request.auth!.tenantId, userId: request.auth!.userId, eventType: "beta.feedback", correlationId: parsed.data.correlationId ?? request.id, metadata: { category: parsed.data.category, message: parsed.data.message, appVersion: parsed.data.appVersion, platform: parsed.data.platform, module: parsed.data.module } } }); return reply.code(201).send({ id: event.id, createdAt: event.createdAt }); });
  app.setErrorHandler(async (error, request, reply) => { await audit(prisma, request, "error"); return reply.code((error as { statusCode?: number }).statusCode ?? 500).send({ error: "request_failed", requestId: request.id }); });
  return app;
}
