import type { PrismaClient } from "@prisma/client";
import { salesSummary } from "./domain.js";
import { stripSecrets } from "./security.js";

const range = (from?: string, to?: string) => ({ ...(from || to ? { date: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {}) });
const daysAgo = (date: string, days: number) => { const value = new Date(`${date}T12:00:00.000Z`); value.setUTCDate(value.getUTCDate() - days); return value.toISOString().slice(0, 10); };
const byCurrency = (transactions: Array<{ type: string; status: string; amount: number; currency: string }>) => Object.entries(transactions.filter((item) => item.status === "completed").reduce<Record<string, { income: number; expenses: number; transfers: number; completedCount: number }>>((summary, item) => { const bucket = summary[item.currency] ?? { income: 0, expenses: 0, transfers: 0, completedCount: 0 }; if (item.type === "income") bucket.income += item.amount; if (item.type === "expense") bucket.expenses += item.amount; if (item.type === "transfer") bucket.transfers += item.amount; bucket.completedCount += 1; summary[item.currency] = bucket; return summary; }, {})).map(([currency, value]) => ({ currency, ...value, net: value.income - value.expenses }));

export async function buildAssistantSnapshot(prisma: PrismaClient, userId: string, options: { from?: string; to?: string; includeTransactions?: boolean; includeCalls?: boolean; includeEnglish?: boolean; includeSales?: boolean; mode?: "summary" | "full" }) {
  const [accounts, transactions, categories, obligations, english, leads, calls, offers, followUps, dailyGoals, measurements, workouts, workoutExercises, exerciseSets, basketball, recovery, checkpoints, roadmap] = await Promise.all([
    prisma.account.findMany({ where: { userId }, orderBy: { createdAt: "asc" } }),
    prisma.transaction.findMany({ where: { userId, ...range(options.from, options.to) }, orderBy: { date: "desc" }, take: options.mode === "full" || options.includeTransactions ? 2000 : 30 }),
    prisma.category.findMany({ where: { userId } }), prisma.obligation.findMany({ where: { userId }, orderBy: { dueDate: "asc" } }),
    prisma.englishProgress.findMany({ where: { userId, ...range(options.from, options.to) }, orderBy: { date: "desc" }, take: 90 }),
    prisma.lead.findMany({ where: { userId }, orderBy: { createdAt: "desc" } }),
    prisma.callActivity.findMany({ where: { userId, ...(options.from || options.to ? { dateTime: { ...(options.from ? { gte: new Date(`${options.from}T00:00:00.000Z`) } : {}), ...(options.to ? { lte: new Date(`${options.to}T23:59:59.999Z`) } : {}) } } : {}) }, orderBy: { dateTime: "desc" }, take: options.mode === "full" || options.includeCalls ? 2000 : 1000 }),
    prisma.offer.findMany({ where: { userId }, orderBy: { updatedAt: "desc" } }), prisma.followUp.findMany({ where: { userId }, orderBy: { date: "asc" } }), prisma.dailyGoal.findMany({ where: { userId, ...range(options.from, options.to) }, orderBy: { date: "desc" } }),
    prisma.sportMeasurement.findMany({ where: { userId }, orderBy: { date: "asc" }, take: 500 }), prisma.workoutSession.findMany({ where: { userId }, orderBy: { date: "desc" }, take: 1000 }), prisma.workoutExercise.findMany({ where: { userId }, take: 5000 }), prisma.exerciseSet.findMany({ where: { userId }, take: 20000 }), prisma.basketballSession.findMany({ where: { userId }, orderBy: { date: "desc" }, take: 1000 }), prisma.recoveryCheckIn.findMany({ where: { userId }, orderBy: { date: "desc" }, take: 365 }), prisma.sportCheckpoint.findMany({ where: { userId }, orderBy: { date: "asc" } }), prisma.sportRoadmapProgress.findMany({ where: { userId }, take: 90 }),
  ]);
  const moneyByCurrency = byCurrency(transactions);
  const accountBalances = accounts.map((account) => { const accountRows = transactions.filter((item) => item.accountId === account.clientId && item.status === "completed" && item.currency === account.currency); const incoming = accountRows.filter((item) => item.type === "income").reduce((sum, item) => sum + item.amount, 0); const outgoing = accountRows.filter((item) => item.type === "expense" || item.type === "transfer").reduce((sum, item) => sum + item.amount, 0); const incomingTransfers = transactions.filter((item) => item.transferToAccountId === account.clientId && item.status === "completed" && item.currency === account.currency).reduce((sum, item) => sum + item.amount, 0); return { accountId: account.clientId, currency: account.currency, openingBalance: account.initialBalance, calculatedBalance: account.initialBalance + incoming - outgoing + incomingTransfers }; });
  const sales = salesSummary(calls, offers);
  const sourceStats = leads.reduce<Record<string, { leads: number; calls: number; won: number }>>((stats, lead) => { const row = stats[lead.source] ?? { leads: 0, calls: 0, won: 0 }; row.leads += 1; row.calls += calls.filter((call) => call.leadId === lead.clientId).length; row.won += offers.some((offer) => offer.leadId === lead.clientId && offer.status === "won") ? 1 : 0; stats[lead.source] = row; return stats; }, {});
  const categoryStats = transactions.filter((item) => item.type === "expense" && item.status === "completed").reduce<Record<string, Record<string, number>>>((stats, item) => { const currency = stats[item.currency] ?? {}; const key = item.categoryId ?? "uncategorized"; currency[key] = (currency[key] ?? 0) + item.amount; stats[item.currency] = currency; return stats; }, {});
  const firstMeasurement = measurements.find((item) => item.weightKg != null || item.waistCm != null); const latestMeasurement = measurements.at(-1); const exerciseMap = new Map(workoutExercises.map((item) => [item.clientId, item])); const completedWorkouts = workouts.filter((item) => item.completed && item.workoutType === "gym"); const weekStart = daysAgo(new Date().toISOString().slice(0, 10), 6); const weeklyTrainingVolume = exerciseSets.filter((set) => set.completed && !set.warmup).filter((set) => { const exercise = exerciseMap.get(set.workoutExerciseClientId); const session = exercise ? workouts.find((item) => item.clientId === exercise.workoutSessionClientId) : undefined; return session?.completed && session.date >= weekStart; }).reduce((sum, set) => sum + set.weight * set.repetitions, 0); const strength = exerciseSets.filter((set) => set.completed && !set.warmup && set.weight > 0 && set.repetitions > 0 && set.repetitions <= 12).map((set) => { const exercise = exerciseMap.get(set.workoutExerciseClientId); return { exercise: exercise?.nameSnapshot ?? "Упражнение", weight: set.weight, repetitions: set.repetitions, estimatedOneRepMax: Math.round(set.weight * (1 + set.repetitions / 30) * 10) / 10 }; }).sort((a, b) => b.estimatedOneRepMax - a.estimatedOneRepMax).slice(0, 5); const latestRecovery = recovery[0] ?? null;
  const today = new Date().toISOString().slice(0, 10);
  const result = { version: "personal-tracker-assistant-snapshot-v2", generatedAt: new Date().toISOString(), period: { from: options.from ?? null, to: options.to ?? null }, money: { byCurrency: moneyByCurrency, accounts: accountBalances, obligations: obligations.map((item) => ({ id: item.clientId, totalAmount: item.totalAmount, paidAmount: item.paidAmount, remaining: Math.max(0, item.totalAmount - item.paidAmount), currency: item.currency, dueDate: item.dueDate, status: item.status })) }, english: { latest: english[0] ?? null, progress: english[0]?.overallProgress ?? 0, completedDays: english[0]?.completedDays ?? 0, streak: english[0]?.streak ?? 0, studyMinutes: english[0]?.studyMinutes ?? 0 }, sales: { ...sales, leads: leads.length, followUps: { today: followUps.filter((item) => item.status !== "completed" && item.date === today).length, overdue: followUps.filter((item) => item.status !== "completed" && item.date < today).length, completed: followUps.filter((item) => item.status === "completed").length }, sourceStats, categoryStats }, sport: { currentWeightKg: latestMeasurement?.weightKg ?? null, weightChangeKg: firstMeasurement?.weightKg != null && latestMeasurement?.weightKg != null ? latestMeasurement.weightKg - firstMeasurement.weightKg : null, currentWaistCm: latestMeasurement?.waistCm ?? null, waistChangeCm: firstMeasurement?.waistCm != null && latestMeasurement?.waistCm != null ? latestMeasurement.waistCm - firstMeasurement.waistCm : null, gymSessions: completedWorkouts.length, basketballSessions: basketball.length, roadmapCompletion: roadmap.length ? Math.round(roadmap.filter((item) => item.status === "completed").length / roadmap.length * 100) : null, weeklyTrainingVolume, latestStrength: strength, recovery: latestRecovery ? { date: latestRecovery.date, sleepHours: latestRecovery.sleepHours, energy: latestRecovery.energy, sleepQuality: latestRecovery.sleepQuality, jointPain: latestRecovery.jointPain, motivation: latestRecovery.motivation } : null, checkpoints: checkpoints.filter((item) => item.completed).length }, dailyGoals, recentOperations: transactions.slice(0, 10), nextActions: followUps.filter((item) => item.status !== "completed").slice(0, 10) };
  const payload = { ...result, ...(options.includeTransactions || options.mode === "full" ? { transactions } : {}), ...(options.includeCalls || options.mode === "full" ? { calls } : {}), ...(options.includeEnglish || options.mode === "full" ? { englishRecords: english } : {}), ...(options.includeSales || options.mode === "full" ? { leads, offers, followUps } : {}), ...(options.mode === "full" ? { sportMeasurements: measurements, workoutSessions: workouts, workoutExercises, exerciseSets, basketballSessions: basketball, recoveryCheckIns: recovery, sportCheckpoints: checkpoints, sportRoadmapDays: roadmap } : {}) };
  return stripSecrets(payload, options.mode === "full");
}
